version: 2

# ------------------------------------------------------------------------------
# Variables

aliases:
  - &setup_prerequisites
    name: Setup prequisites
    command: |
      mkdir -p ~/.aws/
      echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      echo "[$AWS_PROFILE]" >> ~/.aws/credentials
      echo "aws_access_key_id = $AWS_ACCESSKEY" >> ~/.aws/credentials
      echo "aws_secret_access_key = $AWS_SECRET_KEY" >> ~/.aws/credentials
      echo "region = $AWS_REGION" >> ~/.aws/credentials
      sudo apt-get update
      sudo apt-get install git
      sudo apt-get install unzip
      export VER="1.5.1"
      wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
      unzip packer_${VER}_linux_amd64.zip
      sudo mv packer /usr/local/bin
      sudo ln -nfs /usr/local/bin/packer /usr/local/bin/packer-io
      rm packer_${VER}_linux_amd64.zip
jobs:
  build-and-deploy-ami:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - run:
          <<: *setup_prerequisites
      - checkout
      - run:
          name: Build and Deploy AMI
          command: make
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy-ami:
          filters:
            branches:
              only: master
  hourly:
    triggers:
      - schedule:
          cron: "0 0 0/1 1/1 * ? *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-deploy-ami
